back4app/parse-dashboard

Parse-Dashboard/app.js, src/components/back4App/Header/headerNavData.js, src/dashboard/Dashboard.js, src/dashboard/Data/Browser/BrowserTable.react.js
Reverts back4app/parse-dashboard#35
=> Revert "Fix wrong url"

deploy-homolog.sh, deploy-prod.sh, package.json, webpack/homolog.config.js, webpack/publish.config.js
Improves the deployment time by removing 2 unused webpack builds from the homolog deployment script and 1 build from the production deployment script.
=> Improve deployment time

src/components/B4ACodeTree/B4ACodeTree.react.js, src/dashboard/Data/CloudCode/B4ACloudCode.react.js
* Feat: change cloud code learn more link
* Feat: add a dynamic cURL to call the example cloud code
* Fix: API URL
=> Change learn more link

src/components/Sidebar/zendeskSettings.js
Reverts back4app/parse-dashboard#115
=> Revert "fix: Zendesk console error"

src/components/BrowserRow/BrowserRow.react.js, src/components/DateTimePicker/DateTimePicker.react.js, src/dashboard/B4aHubPublishPage/B4aHubPublishPage.react.js, src/dashboard/Data/Browser/BrowserTable.react.js
preventing update for expiration date, as it is readOnly attribute
=> Set expiration date via dashboard on session class

src/dashboard/B4aHubPublishPage/B4aHubPublishPage.react.js
=> Fixing typo

src/dashboard/Data/Browser/Browser.react.js
Showing an error note on clone rows error
=> Clone rows do not work in User class and other classes with unique values

src/lib/ParseApp.js
removed checkType param from csv
=> Import does not work when a string field has a number beginning with 0

src/dashboard/Push/PushNew.react.js
Hiding contact us message when locales messages are set.
=> Push Locales - hiding "contact us message" 

src/components/BrowserRow/BrowserRow.react.js, src/dashboard/Data/Browser/BrowserTable.react.js
Added cancel button for cancelling "add new row" operation
=> Added cancel button for aborting "add new row" operation

src/dashboard/Data/Browser/B4ABrowserToolbar.react.js, src/dashboard/Data/Browser/Browser.react.js, src/dashboard/Data/Browser/BrowserTable.react.js
- Disable clone option of standard classes
- allowing user to edit clone rows fields when error code is 137 ( duplicated Error )
=> Clone rows with unique values

src/components/FlowView/FlowView.react.js, src/dashboard/Settings/GeneralSettings.react.js
User is not required to click on bottom footer "save changes".
Updating collaborators on "Permission's modal" close.
=> Changed add collaborator flow

src/dashboard/Data/Browser/Browser.react.js
Added new 1st step on tour flow
=> Added new step in onboarding tour

src/dashboard/Data/Browser/Browser.react.js
=> Tour: Placing div correctly on step 5

src/components/Tour/Tour.react.js
increased waiting time to check for component rendering
=> Tour: not showing for the first time

src/components/BrowserCell/BrowserCell.react.js
=> Greying out "(auto)" text for new rows

src/dashboard/Data/Browser/Browser.react.js, src/dashboard/Data/Browser/Browser.scss
Showing spinner in place of "Next" text when next component is not ready,
=> Tour: show spinner next component not ready

src/dashboard/Settings/Collaborators.react.js
Confirming delete action for removing collaborator
=> Showing confirm modal before removing collaborator

src/dashboard/Data/Browser/BrowserTable.react.js
- removed extra space for new row & cloned rows
- updated conditions for wrapTop to get editor placed correctly
=> removed extra space on new row & cloned rows

src/dashboard/DashboardView.react.js
=> Fix Sidebar Menus

src/components/ColumnsConfiguration/ColumnsConfiguration.react.js, src/dashboard/Data/Browser/B4ABrowserToolbar.react.js, src/dashboard/Data/Browser/Browser.react.js, src/dashboard/Data/Browser/DataBrowser.react.js, src/lib/validateCLPEntry.js
=> Reorganise browser toolbar

src/dashboard/Settings/Collaborators.react.js
Fixed bug for add collaborators.
This is a PR for story :- [Story link](https://www.pivotaltracker.com/story/show/178286739)
=> Add collaborators button bug.

package-lock.json, package.json, src/components/B4ACloudCodeView/B4ACloudCodeView.react.js, src/components/B4ACodeTree/B4ACodeTree.react.js, src/components/B4ACodeTree/B4ATreeActions.js, src/lib/axios.js
Large files truncate on the code view in cloud code and an option to open the file in CodePen or Blank tab.
=> Opening Big Files on Cloud Code makes the dashboard to freeze

src/components/BrowserCell/BrowserCell.react.js, src/components/DateTimeEditor/DateTimeEditor.react.js
The fix for copy pasting of date values.
=> Pasting date value - Parse Dashboard

Parse-Dashboard/parse-dashboard-config.json, src/components/BrowserCell/BrowserCell.react.js
Fix the bug related to array of pointers.
=> Bug when opening User Class

src/components/DateTimeEditor/DateTimeEditor.react.js
It looks like it's getting my timezone (UTC -3) when I'm pasting the date. (see attachment)
=> Copy & Paste date values

src/components/B4ACodeTree/B4ACodeTree.react.js
Reverts back4app/parse-dashboard#338
=> Revert "Allow empty file on cloud code"

src/dashboard/Apps/AppsIndex.react.js, src/dashboard/Dashboard.js, src/lib/AppsManager.js
Reverts back4app/parse-dashboard#342
=> Revert "Apps page getting stuck"

src/components/Toolbar/Toolbar.react.js, src/components/Toolbar/Toolbar.scss
=> removed play button

src/components/DataBrowserHeader/DataBrowserHeader.react.js, src/components/DataBrowserHeader/DataBrowserHeader.scss
https://www.pivotaltracker.com/story/show/178990719
=> Column Hover Format info Tooltip

src/dashboard/Apps/AppsIndex.react.js, src/dashboard/Apps/AppsIndex.scss
https://www.pivotaltracker.com/story/show/179187797
=> Improve UX: app's card hover cursor in /apps page

src/components/BrowserRow/BrowserRow.react.js
https://www.pivotaltracker.com/story/show/179187789
=> Disable checkbox for new row & edit clone rows

src/dashboard/IndexManager/IndexManager.react.js, src/dashboard/IndexManager/IndexManager.scss
=> change icon in Index Manager

src/dashboard/Data/Browser/Browser.react.js
https://user-images.githubusercontent.com/44117648/133626821-94495068-ccf8-4e06-adc1-3956bf4e7eee.mp4
=> Fixed error note on adding required column

src/components/B4ACodeTree/B4ACodeTree.react.js
=> https://www.pivotaltracker.com/story/show/179694218

src/components/B4ACloudCodeView/B4ACloudCodeView.react.js, src/components/CodeEditor/CodeEditor.react.js
Reverts back4app/parse-dashboard#482
=> Revert "Bugfix/180292351"

src/components/CodeEditor/CodeEditor.react.js
Tracker [https://www.pivotaltracker.com/story/show/180292351](https://www.pivotaltracker.com/story/show/180292351)
=> Cloud code undo fix

jsconfig.json, src/components/FlowView/FlowView.react.js, src/dashboard/Data/Browser/Browser.react.js, src/dashboard/Settings/GeneralSettings.react.js, src/dashboard/Settings/Util/getPromiseList.js, src/lib/ParseApp.js
https://www.pivotaltracker.com/story/show/180781107
=> [App Settings] Revert option.

src/components/FlowView/FlowView.react.js
https://www.pivotaltracker.com/story/show/180781081
=> [Settings] Push notification screen not working

src/components/FlowView/FlowView.react.js, src/dashboard/Push/PushNew.react.js
https://www.pivotaltracker.com/story/show/180837607
=> fix Push New screen field change

src/components/FlowView/FlowView.react.js, src/dashboard/Settings/GeneralSettings.react.js
https://www.pivotaltracker.com/story/show/180837595
=> [Settings] Validation last digit

src/dashboard/Settings/Modals/transferAppModal.react.js
https://www.pivotaltracker.com/story/show/180837625
=> Redirect user to /apps after transfer App

src/components/FlowFooter/FlowFooter.scss, src/components/FlowView/FlowView.react.js, src/components/FlowView/FlowView.scss, src/dashboard/Push/Push.scss, src/dashboard/Settings/Settings.scss
https://www.pivotaltracker.com/story/show/180988029
=> Cannot see complete App settings page, if we have a lot of changes due to bottom bar.

src/components/B4ALabelTemplate/B4ALabelTemplate.react.js, src/components/B4ALabelTemplate/B4ALabelTemplate.scss, src/components/CodeEditor/CodeEditor.react.js, src/components/Sidebar/Sidebar.scss, src/components/SlowQueriesFilter/SlowQueriesFilter.react.js, src/components/SlowQueriesFilter/SlowQueriesFilter.scss, src/dashboard/Analytics/SlowQueries/SlowQueries.react.js
Reverts back4app/parse-dashboard#578
=> Revert "Fix merge changes"

src/dashboard/Dashboard.js, src/dashboard/DashboardView.react.js
=> remove features

src/components/CodeEditor/CodeEditor.react.js, src/dashboard/Data/Playground/Playground.react.js
https://github.com/orgs/back4app/projects/1/views/1?pane=issue&itemId=53553248
=> fix: pass filename to editor

src/components/B4ACodeTree/B4ACodeTree.react.js, src/components/B4ACodeTree/B4ATreeActions.js, src/components/Toggle/B4aTabToggle.scss, src/dashboard/B4aConnectPage/B4aConnectPage.react.js, src/dashboard/Dashboard.js, src/lib/CloudCodeChanges.js
=> Cloud code bugs

deploy-homolog.sh, src/dashboard/DashboardView.react.js
=> Removing blockchain

src/components/DataBrowserHeaderBar/DataBrowserHeaderBar.scss, src/components/Field/Field.scss, src/components/FormTableCollab/FormTableCollab.scss, src/dashboard/Data/Browser/Browser.scss, src/dashboard/ServerSettings/ServerSettings.react.js, src/dashboard/Settings/Collaborators.react.js
=> Minor adjustments

src/components/Field/Field.scss, src/components/FormTableCollab/FormTableCollab.scss
=> Layout adjustments

src/dashboard/Data/Browser/Browser.react.js
=> remove postgresql modal

Parse-Dashboard/app.js, Parse-Dashboard/index.ejs, Parse-Dashboard/login.ejs
=> change page title

src/dashboard/Apps/AppsIndex.react.js, src/dashboard/B4aAdminPage/B4aAdminModal.js, src/dashboard/B4aAdminPage/B4aAdminPage.react.js, src/dashboard/B4aAdminPage/B4aAdminPage.scss, src/dashboard/Dashboard.js, src/dashboard/DashboardView.react.js, src/dashboard/Data/Browser/Browser.react.js, src/dashboard/Settings/DashboardSettings/DashboardSettings.react.js, src/stylesheets/b4aCustomSweetalert.scss, src/stylesheets/swalCustom.css
https://www.pivotaltracker.com/story/show/188357313
=> Admin screen in new dashboard

package.json
=> updating react-components package

src/dashboard/Data/Browser/Browser.react.js
https://www.pivotaltracker.com/story/show/188447876/comments/242833323
=> fix: filtered query export all [old dashboard]

src/dashboard/Data/Browser/Browser.react.js
https://www.pivotaltracker.com/story/show/188447876/comments/242833299
=> fix: exporting a large set of data

src/dashboard/Data/Browser/Browser.react.js
https://www.pivotaltracker.com/story/show/188447876/comments/242833299
=> fix: export all large data csv broken lines[old dashboard]

src/components/PermissionsDialog/B4aPermissionsDialog.react.js, src/components/PermissionsDialog/PermissionsDialog.react.js
Reverts back4app/parse-dashboard#638
=> Revert "Revert "CLP modal fixes""

src/dashboard/Dashboard.js
=> updating path - parse dashboard navbar

src/components/Pill/Pill.scss
https://www.pivotaltracker.com/story/show/188528124
=> Files links not properly  shown

src/dashboard/Data/Browser/B4ABrowserToolbar.react.js
=> fix clp background key strokes

src/components/Toolbar/Toolbar.scss, src/dashboard/Data/Browser/B4ABrowserToolbar.react.js
https://www.pivotaltracker.com/story/show/188604134
=> CLP issue when a field is selected in background[New dashboard]

src/dashboard/Settings/Fields/ManageAppFields.react.js
=> Removing mongo version

src/dashboard/Settings/Fields/ManageAppFields.react.js
Reverts back4app/parse-dashboard#658
=> Revert "Removing mongo version"

Parse-Dashboard/index.ejs
=> Remove wrong text

package.json, src/lib/back4app2.js
https://www.pivotaltracker.com/story/show/188710022
=> bump up navbar version and include avatar in request call

package.json, src/dashboard/Dashboard.js
https://www.pivotaltracker.com/story/show/188710022
=> AiAgentMenu: update navbar

package.json
https://www.pivotaltracker.com/story/show/188710022
=> AiAgentMenu: update version

src/components/BrowserCell/BrowserCell.react.js
https://www.pivotaltracker.com/story/show/188480775
=> When array of Pointers or Relations are not valid, Dashboard Crashes.

src/dashboard/Apps/AppsIndex.scss, src/dashboard/Dashboard.js
https://www.pivotaltracker.com/story/show/188824524
https://back4appcommunity.slack.com/archives/C014WGKQXEH/p1737901353980409
=> Fix horizontal scrollbar on parse-dashboard due to navbar

src/dashboard/Data/AppOverview/AppOverview.react.js, src/dashboard/Data/AppOverview/AppPerformanceCard.react.js
https://back4app.slack.com/archives/C026WHKJS2D/p1743085508728529
=> fix: nextContext app state update

src/dashboard/Settings/GeneralSettings.react.js
=> removing opendb_connection_string

Parse-Dashboard/app.js, Parse-Dashboard/index.ejs, Parse-Dashboard/login.ejs, src/dashboard/Dashboard.js, src/lib/amplitudeEvents.js
=> Removing LogRocket
